# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_ingest: # this can be any name you choose
    resource_class: small
    executor: 
      name: python/default # use the default executor defined within the orb
      tag: '3.11'
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: poetry show
          command: poetry show
      - run:
          name: run save_bot ingestor
          no_output_timeout: 20m
          command: poetry run python src/main.py
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  main:
    jobs:
      - build_and_ingest