# This workflow runs bot_injest every hour

name: Bot Injestor Job

# Controls when the action will run. Workflow runs when manually triggered using the UI
# according to the schedule
# on:
#   schedule:
#     - cron: "0 */1 * * *" #runs every hour
#   workflow_dispatch: # adds manual run button to UI

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
          cache: "poetry"
      - run: poetry install
      - run: poetry show

      - name: Run injestor script
        env:
          DB_URL: ${{ secrets.DB_URL }}
          TWTR_BEARER_TOKEN: ${{ secrets.TWTR_BEARER_TOKEN }}
          LOOKBACK_HOURS: ${{ secrets.LOOKBACK_HOURS }}
        run: poetry run python src/main.py
